// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhtqihgxpjrcwxoffuzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhodHFpaGd4cGpyY3d4b2ZmdXpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNDg3MDksImV4cCI6MjA3NDcyNDcwOX0.vLE0qFngy6BCwwivq_lF7eG6u7pUYkAzKLVFXS0wH0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});